const allProducts = [
  { image: "Bracelet Rainbow AS.jpg", alt: "Rainbow", description: "Rainbow | Size: Adult Small | $0.50" },
  { image: "Bracelet Rainbow AS.jpg", alt: "Rainbow", description: "Rainbow | Size: Adult Medium | $0.50" },
  { image: "Tropical Punch AS.jpg", alt: "Tropical Punch", description: "Tropical Punch | Size: Adult Small | $0.50" },
  { image: "Tropical Punch AS.jpg", alt: "Tropical Punch", description: "Tropical Punch | Size: Adult XL | $0.75" },
  { image: "Citrus.jpg", alt: "Citrus", description: "Citrus | Size: Kid XS | $0.50" },
  { image: "Watermelon.jpg", alt: "Watermelon", description: "Watermelon | Size: Kid XS | $0.50" },
  { image: "Watermelon.jpg", alt: "Watermelon", description: "Watermelon | Size: Kid Small | $0.50" },
  { image: "Blueser.jpg", alt: "Blueser", description: "Blueser | Size: Adult Small | $0.50" },
  { image: "LadyBug.jpg", alt: "LadyBug", description: "LadyBug | Size: Kid Large | $0.50" },
  { image: "Flower.jpg", alt: "Flower", description: "Flower | Size: Kid XS | $0.50" },
  { image: "Spooky.jpg", alt: "Spooky", description: "Spooky | Size: Kid Small | $0.50" },
  { image: "Thunder and Lightning.jpg", alt: "Thunder and Lightning", description: "Thunder & Lightning | Size: Adult SM | $0.50" },
  { image: "Carnival.jpg", alt: "Carnival", description: "Carnival | Size: Kid Small | $0.50" },
  { image: "Green Thunder.jpg", alt: "Green Thunder", description: "Green Thunder | Size: Kid Medium | $0.50" },
  { image: "French.jpg", alt: "French", description: "French | Size: Kid XS | $0.50" },
  { image: "blue punch.jpg", alt: "Blue Punch", description: "Blue Punch | Size: Kid Small | $0.50" },
  { image: "fighter.jpg", alt: "Fighter", description: "Fighter | Size: Kid XS | $0.75" },
  { image: "sunset.jpg", alt: "Sunset", description: "Sunset | Size: Adult Large | $0.75" },
  { image: "Tropical Fish.jpg", alt: "Tropical Fish", description: "Tropical Fish | Size: Kid XS | $0.50" },
  { image: "Scary Pumpkin.jpg", alt: "Scary Pumpkin", description: "Scary Pumpkin | Size: Kid Large | $0.50" },
  { image: "Valentine.jpg", alt: "Valentine", description: "Valentine | Size: Kid Small | $0.50" },
  { image: "Valentine.jpg", alt: "Valentine", description: "Valentine | Size: Adult Small | $0.50" },
  { image: "Viking.jpg", alt: "Viking", description: "Viking | Size: Kid Medium | $0.50" },
  { image: "Easter.jpg", alt: "Easter", description: "Easter | Size: Kid Medium | $0.50" },
  { image: "Red Hot.jpg", alt: "Red Hot", description: "Red Hot | Size: Kid Medium | $0.50" },
  { image: "Raddish.jpg", alt: "Raddish", description: "Raddish | Size: Kid Small | $0.50" },
  { image: "Spring.jpg", alt: "Spring", description: "Spring | Size: Kid Large | $0.50" },
  { image: "Mario.jpg", alt: "Mario", description: "Mario | Size: Kid Large | $0.50" },
  { image: "Blue Tiger.jpg", alt: "Blue Tiger", description: "Blue Tiger | Size: Kid Large | $0.50" },
  { image: "Race Car.jpg", alt: "Race Car", description: "Race Car | Size: Kid Large | $0.50" },
  { image: "Princess.jpg", alt: "Princess", description: "Princess | Size: Kid Medium | $0.50" },
  { image: "Orange.jpg", alt: "Orange", description: "Orange | Size: Kid Medium | $0.50" },
  { image: "Blue All Around.jpg", alt: "Blue All Around", description: "Blue All Around | Size: Adult Small | $0.50" },
  { image: "Chili Pepper.jpg", alt: "Chili Pepper", description: "Chili Pepper | Size: Kid Small | $0.50" },
  { image: "Sunrise.jpg", alt: "Sunrise", description: "Sunrise | Size: Kid Medium | $0.50" },
  { image: "Jet.jpg", alt: "Jet", description: "Jet | Size: Kid Medium | $0.50" },
  { image: "Pink Tiger.jpg", alt: "Pink Tiger", description: "Pink Tiger | Size: Kid Large | $0.50" },
  { image: "Neon.jpg", alt: "Neon", description: "Neon | Size: Kid Large | $0.50" },
  { image: "Electric.jpg", alt: "Electric", description: "Electric | Size: Kid small | $0.50" },
  { image: "Azalea.jpg", alt: "Azalea", description: "Azalea | Size: Kid XS | $0.50" },
  { image: "Cool Runner.jpg", alt: "Cool Runner", description: "Cool Runner | Size: Kid XS | $0.50" },
  { image: "Scarecrow.jpg", alt: "Scarecrow", description: "Scarecrow | Size: Kid XS | $0.50" },
  { image: "Castle.jpg", alt: "Castle", description: "Castle | Size: Kid XS | $0.50" }
{ image: "Lime.jpg", alt: "Lime", description: "Lime | Size: Kid XS | $0.50" }
];